## **Data Info**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

In [3]:
products_data = pd.read_csv("/content/products_dataset.csv")
orders_data = pd.read_csv("/content/orders_dataset.csv")
order_item_data = pd.read_csv("/content/order_items_dataset.csv")
customers_data = pd.read_csv("/content/customers_dataset.csv")

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
print("Orders Data")
print("Dimension:", orders_data.shape)
display(orders_data.head())

print("Customer Data")
print("Dimension:", customers_data.shape)
display(customers_data.head())

print("Orders Item Data")
print("Dimension:", order_item_data.shape)
display(order_item_data.head())

print("Product Data")
print("Dimension:", products_data.shape)
display(products_data.head())

Orders Data
Dimension: (99441, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Customer Data
Dimension: (99441, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Orders Item Data
Dimension: (112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Product Data
Dimension: (32951, 9)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

## **1. Merging the data into one dataframe**
a. First, merge orders_data and order_item_data
b. Finally, Merge the first step with product_data and customer_data

In [24]:
#Merger order data dengan order item data
mergedata1 = order_item_data.merge(orders_data, how='left',on='order_id')
print('Dimension', mergedata1.shape)
mergedata1.head()

Dimension (112650, 14)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [25]:
#merger semua data
mergedata2 = mergedata1.merge(products_data, how='left', on='product_id')
print("Dimension" , mergedata2.shape) 
mergedata2.head()

Dimension (112650, 22)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,order_delivered_customer_date,order_estimated_delivery_date,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,2017-09-20 23:43:48,2017-09-29 00:00:00,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,2017-05-12 16:04:24,2017-05-15 00:00:00,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,2018-01-22 13:19:16,2018-02-05 00:00:00,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,2018-08-14 13:32:39,2018-08-20 00:00:00,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,2017-03-01 16:42:31,2017-03-17 00:00:00,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0

In [26]:
#merger semua data (jumlah baris tetap 112650, kolom bertambah)
final_data= mergedata2.merge(customers_data, how='left' , on='customer_id')
print("Dimension" , final_data.shape)
final_data.head()

Dimension (112650, 26)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,598.0,4.0,650.0,28.0,9.0,14.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,239.0,2.0,30000.0,50.0,30.0,40.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,695.0,2.0,3050.0,33.0,13.0,33.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,480.0,1.0,200.0,16.0,10.0,15.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,409.0,1.0,3750.0,35.0,40.0,30.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP

## **2. Customize the type of the columns that should be**
- datetime, int, float, object

In [27]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112650 entries, 0 to 112649
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  object
 10  order_approved_at              112635 non-null  object
 11  order_delivered_carrier_date   111456 non-null  object
 12  order_delivered_customer_date  110196 non-null  object
 13  order_estimated_delivery_date  112650 non-null  object
 14  product_category_name          111047 non-null  object
 15  product_name_lenght            111047 non-null  float64
 16  product_description_lenght     111047 non-null  float64
 17  product_photos_qty             111047 non-null  float64
 18  product_weight_g               112632 non-null  float64
 19  product_length_cm              112632 non-null  float64
 20  product_height_cm              112632 non-null  float64
 21  product_width_cm               112632 non-null  float64
 22  customer_unique_id             112650 non-null  object
 23  customer_zip_code_prefix       112650 non-null  int64
 24  customer_city                  112650 non-null  object
 25  customer_state                 112650 non-null  object
dtypes: float64(9), int64(2), object(15)
memory usage: 23.2+ MB

In [28]:
#mengubah type data yang seharus nya dalam bentuk tanggal (datetime) tetapi masih dalam bentuk object

datetime=['shipping_limit_date', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date' ]

for i in datetime:
  final_data[i] = pd.to_datetime(final_data[i])

In [29]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112650 entries, 0 to 112649
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  datetime64[ns]
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  datetime64[ns]
 10  order_approved_at              112635 non-null  datetime64[ns]
 11  order_delivered_carrier_date   111456 non-null  datetime64[ns]
 12  order_delivered_customer_date  110196 non-null  datetime64[ns]
 13  order_estimated_delivery_date  112650 non-null  datetime64[ns]
 14  product_category_name          111047 non-null  object
 15  product_name_lenght            111047 non-null  float64
 16  product_description_lenght     111047 non-null  float64
 17  product_photos_qty             111047 non-null  float64
 18  product_weight_g               112632 non-null  float64
 19  product_length_cm              112632 non-null  float64
 20  product_height_cm              112632 non-null  float64
 21  product_width_cm               112632 non-null  float64
 22  customer_unique_id             112650 non-null  object
 23  customer_zip_code_prefix       112650 non-null  int64
 24  customer_city                  112650 non-null  object
 25  customer_state                 112650 non-null  object
dtypes: datetime64[ns](6), float64(9), int64(2), object(9)
memory usage: 23.2+ MB

## **3. Check any null values from the merged dataframe**
- clue, using append

In [30]:
final_datanull = final_data.dtypes
final_datanull

order_id                                 object
order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
product_category_name                    object
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
customer_unique_id                       object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
dtype: object

In [31]:
type_null = pd.DataFrame(final_data.dtypes).T.rename(index = {0: 'Columns Type'})
type_null = type_null.append(pd.DataFrame(final_data.isnull().sum()).T.rename(index = {0: 'Amount of Null Values'}))
type_null = type_null.append(pd.DataFrame(final_data.isnull().sum()/final_data.shape[0]*100).T.rename(index = {0: 'Percentage of Null Values'}))
display(type_null)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
Columns Type,object,int64,object,object,datetime64[ns],float64,float64,object,object,datetime64[ns],...,float64,float64,float64,float64,float64,float64,object,int64,object,object
Amount of Null Values,0,0,0,0,0,0,0,0,0,0,...,1603,1603,18,18,18,18,0,0,0,0
Percentage of Null Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.422992,1.422992,0.015979,0.015979,0.015979,0.015979,0.0,0.0,0.0,0.0

In [32]:
type_null.T

,Columns Type,Amount of Null Values,Percentage of Null Values
order_id,object,0,0.0
order_item_id,int64,0,0.0
product_id,object,0,0.0
seller_id,object,0,0.0
shipping_limit_date,datetime64[ns],0,0.0
price,float64,0,0.0
freight_value,float64,0,0.0
customer_id,object,0,0.0
order_status,object,0,0.0
order_purchase_timestamp,datetime64[ns],0,0.0
order_approved_at,datetime64[ns],15,0.013316
order_delivered_carrier_date,datetime64[ns],1194,1.05992
order_delivered_customer_date,datetime64[ns],2454,2.178429
order_estimated_delivery_date,datetime64[ns],0,0.0
product_category_name,object,1603,1.422992
product_name_lenght,float64,1603,1.422992
product_description_lenght,float64,1603,1.422992
product_photos_qty,float64,1603,1.422992
product_weight_g,float64,18,0.015979
product_length_cm,float64,18,0.015979
product_height_cm,float64,18,0.015979
product_width_cm,float64,18,0.015979
customer_unique_id,object,0,0.0
customer_zip_code_prefix,int64,0,0.0
customer_city,object,0,0.0
customer_state,object,0,0.0

## **4. In the merged dataframe, please add new column to get the date and the time (hour) and day name from:**
- order_purchase_timestamp
    - dt.hour -> jam
    - dt.day_name -> hari
- order_delivered_customer_date

In [33]:
final_data.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,598.0,4.0,650.0,28.0,9.0,14.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,239.0,2.0,30000.0,50.0,30.0,40.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,695.0,2.0,3050.0,33.0,13.0,33.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,480.0,1.0,200.0,16.0,10.0,15.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,409.0,1.0,3750.0,35.0,40.0,30.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP

In [34]:
final_data['order_purchase_timestamp'].dt.hour

0          8
1         10
2         14
3         10
4         13
          ..
112645    13
112646    10
112647    17
112648    23
112649    17
Name: order_purchase_timestamp, Length: 112650, dtype: int64

In [35]:
final_data['order_purchase_timestamp'].dt.day_name()

0         Wednesday
1         Wednesday
2            Sunday
3         Wednesday
4          Saturday
            ...
112645       Monday
112646     Saturday
112647       Monday
112648       Monday
112649     Saturday
Name: order_purchase_timestamp, Length: 112650, dtype: object

In [45]:
#mencari jam dan hari
final_data['order_purchase_hour'] = final_data['order_purchase_timestamp'].dt.hour
final_data['order_purchase_day_name'] = final_data['order_purchase_timestamp'].dt.day_name()
final_data.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_purchase_hour,order_purchase_day_name,order_delivered_hour,order_delivered_day_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,9.0,14.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,8,Wednesday,23.0,<bound method PandasDelegate._add_delegate_acc...
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,30.0,40.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,10,Wednesday,16.0,<bound method PandasDelegate._add_delegate_acc...
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,13.0,33.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,14,Sunday,13.0,<bound method PandasDelegate._add_delegate_acc...
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,10.0,15.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,10,Wednesday,13.0,<bound method PandasDelegate._add_delegate_acc...
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,40.0,30.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,13,Saturday,16.0,<bound method PandasDelegate._add_delegate_acc...

In [46]:
#order_delivered_customer_date	
final_data['order_delivered_hour'] = final_data['order_delivered_customer_date'].dt.hour
final_data['order_delivered_day_name'] = final_data['order_delivered_customer_date'].dt.day_name()
final_data.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_purchase_hour,order_purchase_day_name,order_delivered_hour,order_delivered_day_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,9.0,14.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,8,Wednesday,23.0,Wednesday
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,30.0,40.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,10,Wednesday,16.0,Friday
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,13.0,33.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,14,Sunday,13.0,Monday
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,10.0,15.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,10,Wednesday,13.0,Tuesday
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,40.0,30.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,13,Saturday,16.0,Wednesday

## **5.How many unique customer do the transaction in each city?**
- Clue, use pivot table or group by

In [38]:
hasil_pivot = pd.pivot_table(final_data, values='customer_id' , index='customer_city', aggfunc=pd.Series.nunique)
hasil_pivot

                     customer_id
customer_city
abadia dos dourados            3
abadiania                      1
abaete                        12
abaetetuba                    11
abaiara                        2
...                          ...
xinguara                       9
xique-xique                    3
zacarias                       2
ze doca                        5
zortea                         2

[4110 rows x 1 columns]

## **6. Get the top 5 cities that has the highest number of unique customer**
- clue, sorting the data using sort_values

In [39]:
#data 5 terbesar
Get_Top_5= hasil_pivot.reset_index().sort_values(by='customer_id', ascending = False).reset_index(drop=True)
Get_Top_5[:5]

    customer_city  customer_id
0       sao paulo        15402
1  rio de janeiro         6834
2  belo horizonte         2750
3        brasilia         2116
4        curitiba         1510

## **7. At the 5 cities, what time the customer do the transaction? show them in :**
- Average
- Median
- Clue, use pivot table or  group by

In [40]:
g = final_data.groupby('customer_city').agg(customer_id=('customer_id' , 'count'), average_order=('order_purchase_hour', 'mean'), median_order=('order_purchase_hour', 'median'))
g.reset_index().sort_values(by=['customer_id'], ascending=False).head(5).reset_index(drop=True)

    customer_city  customer_id  average_order  median_order
0       sao paulo        17808      14.613544          15.0
1  rio de janeiro         7837      14.624218          15.0
2  belo horizonte         3144      14.864504          15.0
3        brasilia         2392      14.930184          15.0
4        curitiba         1751      15.064535          15.0

In [41]:
g.describe()

        customer_id  average_order  median_order
count   4110.000000    4110.000000   4110.000000
mean      27.408759      14.850761     15.012530
std      319.762531       3.427321      3.680393
min        1.000000       0.000000      0.000000
25%        1.000000      13.000000     13.000000
50%        3.000000      15.000000     15.000000
75%       10.000000      16.714286     17.000000
max    17808.000000      23.000000     23.000000